### ISSUE TITLE
How to Maintain Quality 

### ISSUE THREAD

**Issue by Platin21** [thebennybox-Community/Community-Compiler#11]
- Will we use something like unit-tests to make sure everything works as intended?
- Is code review a thing? 
- When how will be allowed to do that and how will 'we' choose who?
- Clang format or something equal would be nice to maintain readability probably? 
… (something that was in my brain but i lost it)

**Comment by michaelomah** [comment]
I believe Myvar will be reviewing pull requests, not sure about unit tests though, i think having unit tests would be a good idea though

**Comment by Platin21** [comment]
If we make some what should we test?
An would it be enough to include in everything we do a function like `test_xxx` wich goes through every function/method wich the module defines.

**Comment by MyvarHD** [comment]
Testing is a greate idea and it is very practical to implment so thats not a problem, as for Quality  that will be my job, i will reaview all pull req make sure that are up to standart, and i will merge them after problems has been fixed
