### ISSUE TITLE
Intentions with the Language.

### ISSUE THREAD

**Issue by Platin21** [thebennybox-Community/Community-Compiler#4]
So do we make a language more in they way for games or something else ?

**Comment by MyvarHD** [comment]
Education/Fun
Game development

**Comment by Platin21** [comment]
If we want to make it for GameDev it definitely will change the decision what we want to target with our IL first. So it's fundamentally to know that for #2 .

**Comment by MyvarHD** [comment]
Integrating Contructs like GLSL and Unions and propper memmory management is all a good idea for game dev stuff
